### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by mufunyo** [Orcastraw/Aspect#1]
Hi,

I used to link people to orcastraw.com/aspect as a reference for console aspect ratios. It seems the domain is down and the source code for the page that used to be there is here. Could you please post it to your github.io so I can link people to the new URL? It's a great reference!

Thanks for your hard work documenting all this.

**Comment by Orcastraw** [comment]
Sure I'll mirror it on my github.io. It may take a few days as the original was written in rails, but it should be up in a few days. Also, I'm trying to re-purchase the old domain, so in the future I'll have it back on there as well.

**Comment by mufunyo** [comment]
Hi,

Any progress on this?

**Comment by Orcastraw** [comment]
The site has been restored at http://www.orcastraw.party/aspect
A more proper URL, a switch possibly to .net, and better styling are being looked into.
My apologies for the any inconvenience this may have caused.
